# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e8ef3c2c6ce0f965c8992b77b7217d711036081883c63b59c45341dabf7f384649584b84396f3b7fbde6269cc257094dd77c951056967ed3ba3c2c67b91fa6

test:
  secret_key_base: 764f0de2c74f5e6dc38dc98aff16243b417865d03ec4ca47e47d5ad0bfeda888b5bc09042c5d1f36ed0a84d2173d85a48b37087aa088ee8f5edb33bde2ed91aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
